-- =========================================
-- MIGRACIÓN SUPABASE - Sistema de Joyería
-- =========================================
-- Ejecutar este script en el SQL Editor de Supabase
-- URL: https://mvujkbpbqyihixkbzthe.supabase.co/project/_/sql

-- IMPORTANTE: Este script crea todas las tablas necesarias
-- para el sistema de joyería en Supabase (PostgreSQL)

DROP TABLE IF EXISTS movimientos_cuenta CASCADE;
DROP TABLE IF EXISTS imagenes_joya CASCADE;
DROP TABLE IF EXISTS push_subscriptions CASCADE;
DROP TABLE IF EXISTS productos_compuestos CASCADE;
DROP TABLE IF EXISTS variantes_producto CASCADE;
DROP TABLE IF EXISTS historial_estado_pedidos CASCADE;
DROP TABLE IF EXISTS items_pedido_online CASCADE;
DROP TABLE IF EXISTS pedidos_online CASCADE;
DROP TABLE IF EXISTS cierres_caja CASCADE;
DROP TABLE IF EXISTS devoluciones CASCADE;
DROP TABLE IF EXISTS ingresos_extras CASCADE;
DROP TABLE IF EXISTS configuracion_tienda CASCADE;
DROP TABLE IF EXISTS auditoria_inventario CASCADE;
DROP TABLE IF EXISTS reservas_inventario CASCADE;
DROP TABLE IF EXISTS items_venta_dia CASCADE;
DROP TABLE IF EXISTS ventas_dia CASCADE;
DROP TABLE IF EXISTS abonos CASCADE;
DROP TABLE IF EXISTS cuentas_por_cobrar CASCADE;
DROP TABLE IF EXISTS movimientos_inventario CASCADE;
DROP TABLE IF EXISTS items_venta CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS joyas CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL,
  full_name TEXT NOT NULL,
  fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE joyas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  categoria TEXT,
  proveedor TEXT,
  costo NUMERIC NOT NULL CHECK (costo >= 0),
  precio_venta NUMERIC NOT NULL CHECK (precio_venta >= 0),
  moneda TEXT DEFAULT 'CRC',
  stock_actual INTEGER NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
  stock_minimo INTEGER DEFAULT 5 CHECK (stock_minimo >= 0),
  stock_reservado INTEGER DEFAULT 0 CHECK (stock_reservado >= 0),
  ubicacion TEXT,
  estado TEXT DEFAULT 'Activo',
  imagen_url TEXT,
  imagen_public_id TEXT,
  peso_gramos NUMERIC,
  ancho_cm NUMERIC,
  alto_cm NUMERIC,
  largo_cm NUMERIC,
  sku TEXT,
  slug TEXT,
  meta_title TEXT,
  meta_description TEXT,
  visible_en_tienda BOOLEAN DEFAULT TRUE,
  destacado BOOLEAN DEFAULT FALSE,
  orden_tienda INTEGER DEFAULT 0,
  version INTEGER DEFAULT 1,
  fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
  fecha_ultima_modificacion TIMESTAMPTZ DEFAULT NOW(),
  mostrar_en_storefront BOOLEAN DEFAULT TRUE,
  es_producto_variante BOOLEAN DEFAULT FALSE,
  es_producto_compuesto BOOLEAN DEFAULT FALSE
);

CREATE TABLE clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  telefono TEXT,
  cedula TEXT,
  direccion TEXT,
  email TEXT,
  notas TEXT,
  fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
  fecha_ultima_modificacion TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL REFERENCES usuarios(id),
  metodo_pago TEXT NOT NULL,
  subtotal NUMERIC NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  descuento NUMERIC DEFAULT 0 CHECK (descuento >= 0),
  total NUMERIC NOT NULL CHECK (total >= 0),
  efectivo_recibido NUMERIC,
  cambio NUMERIC,
  notas TEXT,
  tipo_venta TEXT DEFAULT 'Contado',
  id_cliente BIGINT REFERENCES clientes(id),
  monto_efectivo NUMERIC DEFAULT 0,
  monto_tarjeta NUMERIC DEFAULT 0,
  monto_transferencia NUMERIC DEFAULT 0,
  fecha_venta TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE items_venta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta BIGINT NOT NULL REFERENCES ventas(id) ON DELETE CASCADE,
  id_joya BIGINT REFERENCES joyas(id),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC NOT NULL CHECK (precio_unitario >= 0),
  subtotal NUMERIC NOT NULL CHECK (subtotal >= 0),
  descripcion_item TEXT
);

CREATE TABLE movimientos_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_joya BIGINT NOT NULL REFERENCES joyas(id),
  tipo_movimiento TEXT NOT NULL,
  cantidad INTEGER NOT NULL,
  motivo TEXT,
  fecha_movimiento TIMESTAMPTZ DEFAULT NOW(),
  usuario TEXT,
  stock_antes INTEGER NOT NULL,
  stock_despues INTEGER NOT NULL
);

CREATE TABLE cuentas_por_cobrar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta BIGINT NOT NULL REFERENCES ventas(id),
  id_cliente BIGINT NOT NULL REFERENCES clientes(id),
  monto_total NUMERIC NOT NULL CHECK (monto_total >= 0),
  monto_pagado NUMERIC DEFAULT 0 CHECK (monto_pagado >= 0),
  saldo_pendiente NUMERIC NOT NULL CHECK (saldo_pendiente >= 0),
  estado TEXT DEFAULT 'Pendiente',
  fecha_vencimiento DATE,
  fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
  fecha_ultima_modificacion TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE abonos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cuenta_por_cobrar BIGINT NOT NULL REFERENCES cuentas_por_cobrar(id) ON DELETE CASCADE,
  monto NUMERIC NOT NULL CHECK (monto > 0),
  metodo_pago TEXT NOT NULL,
  notas TEXT,
  fecha_abono TIMESTAMPTZ DEFAULT NOW(),
  usuario TEXT,
  cerrado BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_cierre TIMESTAMPTZ
);

CREATE TABLE ventas_dia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL REFERENCES usuarios(id),
  metodo_pago TEXT NOT NULL,
  subtotal NUMERIC NOT NULL DEFAULT 0,
  descuento NUMERIC DEFAULT 0,
  total NUMERIC NOT NULL,
  efectivo_recibido NUMERIC,
  cambio NUMERIC,
  notas TEXT,
  tipo_venta TEXT DEFAULT 'Contado',
  id_cliente BIGINT REFERENCES clientes(id),
  monto_efectivo NUMERIC DEFAULT 0,
  monto_tarjeta NUMERIC DEFAULT 0,
  monto_transferencia NUMERIC DEFAULT 0,
  fecha_venta TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE items_venta_dia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta_dia BIGINT NOT NULL REFERENCES ventas_dia(id) ON DELETE CASCADE,
  id_joya BIGINT REFERENCES joyas(id),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC NOT NULL,
  subtotal NUMERIC NOT NULL,
  descripcion_item TEXT
);

CREATE TABLE reservas_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_joya BIGINT NOT NULL REFERENCES joyas(id),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  tipo_reserva TEXT NOT NULL,
  referencia_externa TEXT,
  usuario_reserva TEXT,
  fecha_reserva TIMESTAMPTZ DEFAULT NOW(),
  fecha_expiracion TIMESTAMPTZ,
  estado TEXT DEFAULT 'activa',
  origen TEXT DEFAULT 'tienda_fisica'
);

CREATE TABLE auditoria_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_joya BIGINT NOT NULL REFERENCES joyas(id),
  accion TEXT NOT NULL,
  stock_anterior INTEGER,
  stock_nuevo INTEGER,
  cantidad_cambio INTEGER,
  usuario TEXT,
  origen TEXT,
  referencia TEXT,
  detalles JSONB,
  ip_address TEXT,
  fecha_auditoria TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE configuracion_tienda (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave TEXT NOT NULL UNIQUE,
  valor TEXT,
  tipo_dato TEXT DEFAULT 'string',
  descripcion TEXT,
  categoria TEXT,
  fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
  fecha_modificacion TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE ingresos_extras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL,
  monto NUMERIC NOT NULL CHECK (monto > 0),
  metodo_pago TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  id_usuario BIGINT NOT NULL REFERENCES usuarios(id),
  usuario TEXT,
  cerrado BOOLEAN DEFAULT FALSE,
  fecha_cierre TIMESTAMPTZ,
  fecha_ingreso TIMESTAMPTZ DEFAULT NOW(),
  notas TEXT
);

CREATE TABLE devoluciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta BIGINT NOT NULL REFERENCES ventas(id),
  id_joya BIGINT NOT NULL REFERENCES joyas(id),
  cantidad INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC NOT NULL,
  subtotal NUMERIC NOT NULL,
  motivo TEXT NOT NULL,
  tipo_devolucion TEXT NOT NULL,
  estado TEXT DEFAULT 'Pendiente',
  monto_reembolsado NUMERIC DEFAULT 0,
  metodo_reembolso TEXT,
  id_usuario BIGINT NOT NULL REFERENCES usuarios(id),
  usuario TEXT,
  notas TEXT,
  fecha_devolucion TIMESTAMPTZ DEFAULT NOW(),
  fecha_procesada TIMESTAMPTZ
);

CREATE TABLE cierres_caja (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_cierre TIMESTAMPTZ DEFAULT NOW(),
  id_usuario BIGINT REFERENCES usuarios(id),
  usuario TEXT,
  resumen JSONB,
  total_ventas INTEGER DEFAULT 0,
  total_ingresos NUMERIC DEFAULT 0,
  total_general NUMERIC DEFAULT 0,
  total_efectivo_combinado NUMERIC DEFAULT 0,
  total_transferencia_combinado NUMERIC DEFAULT 0,
  total_tarjeta_combinado NUMERIC DEFAULT 0,
  monto_total_abonos NUMERIC DEFAULT 0,
  monto_total_ingresos_extras NUMERIC DEFAULT 0,
  notas TEXT
);

CREATE TABLE pedidos_online (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_cliente TEXT NOT NULL,
  telefono TEXT,
  email TEXT,
  provincia TEXT,
  canton TEXT,
  distrito TEXT,
  direccion_linea1 TEXT,
  direccion_linea2 TEXT,
  codigo_postal TEXT,
  telefono_envio TEXT,
  subtotal NUMERIC,
  costo_envio NUMERIC,
  total NUMERIC CHECK (total >= 0),
  notas TEXT,
  notas_internas TEXT,
  metodo_pago TEXT,
  comprobante_url TEXT,
  comprobante_public_id TEXT,
  estado TEXT DEFAULT 'pendiente',
  estado_pago TEXT DEFAULT 'pendiente',
  id_usuario_aprobacion BIGINT REFERENCES usuarios(id),
  fecha_aprobacion TIMESTAMPTZ,
  id_venta BIGINT REFERENCES ventas(id),
  fecha_creacion TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE items_pedido_online (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido BIGINT NOT NULL REFERENCES pedidos_online(id) ON DELETE CASCADE,
  id_joya BIGINT REFERENCES joyas(id),
  nombre_producto TEXT,
  precio_unitario NUMERIC,
  cantidad INTEGER CHECK (cantidad > 0),
  subtotal NUMERIC,
  imagen_url TEXT
);

CREATE TABLE historial_estado_pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido BIGINT NOT NULL REFERENCES pedidos_online(id) ON DELETE CASCADE,
  estado_anterior TEXT,
  estado_nuevo TEXT NOT NULL,
  usuario TEXT NOT NULL,
  notas TEXT,
  fecha TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE variantes_producto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto_padre BIGINT NOT NULL REFERENCES joyas(id),
  nombre_variante VARCHAR NOT NULL,
  descripcion_variante TEXT,
  imagen_url TEXT NOT NULL,
  orden_display INTEGER DEFAULT 0,
  activo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE productos_compuestos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto_set BIGINT NOT NULL REFERENCES joyas(id),
  id_producto_componente BIGINT NOT NULL REFERENCES joyas(id),
  cantidad INTEGER NOT NULL DEFAULT 1 CHECK (cantidad > 0),
  orden_display INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario BIGINT NOT NULL REFERENCES usuarios(id),
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  last_used TIMESTAMP DEFAULT NOW()
);

CREATE TABLE imagenes_joya (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_joya BIGINT NOT NULL REFERENCES joyas(id) ON DELETE CASCADE,
  imagen_url TEXT NOT NULL,
  orden_display INTEGER DEFAULT 0,
  es_principal BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE movimientos_cuenta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cuenta_por_cobrar BIGINT NOT NULL REFERENCES cuentas_por_cobrar(id) ON DELETE CASCADE,
  id_venta BIGINT REFERENCES ventas(id),
  tipo TEXT NOT NULL,
  monto NUMERIC NOT NULL CHECK (monto > 0),
  descripcion TEXT,
  fecha_movimiento TIMESTAMPTZ DEFAULT NOW(),
  usuario TEXT
);